### ISSUE TITLE
cy.xpath not available outside the spec files

### ISSUE THREAD

**Issue by sonudavidson** [cypress-io/cypress-xpath#122]
I want to use cy.xpath in the common.js file that has common step definitions. Apparently, I cannot do that. 
I get an error 'cy.xpath is not a function' when I do so.

the common.js file is inside the integration directory but it is not a spec file.
How can I make it work?

thanks in advance.

**Comment by jennifer-shehane** [comment]
Make sure to follow all steps for installation. You need to `require('cypress-xpath')` in your project's `cypress/support/index.js`, there shouldn't be any issue with any files within the `integration` folder if this is done.

**Comment by sonudavidson** [comment]
I use VS Code to write my tests. It's quite strange that it didn't start working until my view is changed to this
![image](https://user-images.githubusercontent.com/5096397/99545939-2b2ba780-29b6-11eb-90f4-04d78e37a3a8.png)

**Comment by sonudavidson** [comment]
![image](https://user-images.githubusercontent.com/5096397/99551276-f02c7280-29bb-11eb-9242-c27e75118f29.png)

**Comment by bahmutov** [comment]
Just added the `types` field to the `package.json` which should solve it, see https://github.com/cypress-io/cypress-xpath#typescript-and-intellisense-support
