### ISSUE TITLE
VS Code doesn't recognize "cy.xpath" method, but the code compiles and the method gets called

### ISSUE THREAD

**Issue by igorgiumellizup** [cypress-io/cypress-xpath#139]
I installed cypress-xpath through yarn and apparently everthing went fine (yarn.lock and package.json files updated). Compiling and testing the project in terminal woks too. But editing the project in Visual Studio Code shows an error when using cy.xpath: "Property 'xpath' does not exist on type 'cy & EventEmitter'.ts(2339)"

How can I make VS Code recognize the .xpath method?

**Comment by bahmutov** [comment]
Added https://github.com/cypress-io/cypress-xpath#typescript-and-intellisense-support
