### ISSUE TITLE
Deprecate Repo

### ISSUE THREAD

**Issue by jordanpowell88** [cypress-io/cypress-xpath#187]
We moved this project to the main Cypress monorepo at `npm/xpath`. We need document in this repo that it is deprecated, triage and old issues and add https://docs.npmjs.com/cli/v8/commands/npm-deprecate/

**Comment by admah** [comment]
TODO: 

[] add npm-deprecate package
[] update the README with new location and link to create issues
[] set repo to archived
[] work through issues using [Icewatch guide](https://github.com/cypress-io/prod-eng-docs/blob/main/cypress-app/ice-watch-process.md)
