### ISSUE TITLE
Can't type() using xpath

### ISSUE THREAD

**Issue by gerardovanegas-eagle** [cypress-io/cypress-xpath#22]
I've tried to use xpath to type() and I'm getting the following error message:
```
CypressError: cy.type() failed because it requires a DOM element.
```

The subject received was:

  > {}

The previous command that ran was:

  > cy.xpath()
![image](https://user-images.githubusercontent.com/45433407/50913242-e8840600-1401-11e9-8ab4-784174362898.png)

this is my code:
```js
describe('Juntoz Test', function () {
  before('Log In first with determined user', function () {
    cy.visit('https://juntoz.com');
    expect(cy).property('xpath').to.be.a('function')
    const emailAddress = Cypress.env('emailAddress')
    const password = Cypress.env('password')
    cy.xpath("//i[@class='fa fa-angle-down pull-right popover-item-icon']").click()
    cy.xpath("//button[@class='btn btn-juntoz ng-scope' and text()='Identificarse']").click()
    cy.xpath("//input[@ng-model='emailLogin']").type(emailAddress, {force:true})
    cy.xpath("//input[@ng-model='passwordLogin']").type(password, {force:true})
})
```

**Comment by bahmutov** [comment]
Are these xpaths even correct? Can you confirm that they work from DevTools console? Why use them at all? You first selector to open the login should be just `cy.get('#btnaccount')` and the other one are similar. Just use jQuery selectors that you have! 

- https://on.cypress.io/best-practices#Selecting-Elements
- https://on.cypress.io/get

**Comment by bahmutov** [comment]
How do you try xpath selectors in devtools console?

**Comment by gerardovanegas-eagle** [comment]
I'm not sure if we are talking about the same thing but I inspect the page and I ctrl+f on the html then paste my xpath, that's how I know it locates the element.

**Comment by jennifer-shehane** [comment]
Yeah, the error does seem to be indicating that the `cy.xpath()` command before the `.type()` did not yield a DOM element, but instead an empty object. 

I personally don't remember that much about xpath anymore, but I noticed this website is public, and inspected the email login to be this html:

```html
<input type="email" class="form-control ng-pristine ng-valid-email ng-invalid ng-invalid-required ng-touched" name="userEmail" required="" placeholder="Email" ng-model="emailLogin">
```

I can also confirm that `ctrl + f` in the Elements tab of the devtools, which you to 'Find by string, selector, or XPath' does indeed highlight this email element.

**Comment by bahmutov** [comment]
If you want to find element in the elements panel of DevTools, then right click and Copy XPath, you can then check it in the DevTools Console using `$x('... xpath ... ')` 
For example

<img width="484" alt="screen shot 2019-01-09 at 4 54 44 pm" src="https://user-images.githubusercontent.com/2212006/50930983-68749500-142f-11e9-9d42-5f6ada0d8266.png">

When I try the XPaths from the given test I get the element

<img width="455" alt="screen shot 2019-01-09 at 4 56 58 pm" src="https://user-images.githubusercontent.com/2212006/50931084-a2459b80-142f-11e9-9935-9199770e224f.png">

**Comment by bahmutov** [comment]
I have added a simple test to show that `cy.xpath(...).type()` is working in https://github.com/cypress-io/cypress-xpath/commit/f9e3a467d17077256c6863bb6c0ab3e1fc818264
