### ISSUE TITLE
Query Xpath working on normal browser, but not in Cypress

### ISSUE THREAD

**Issue by olegario96** [cypress-io/cypress-xpath#25]
I'm trying to running tests with Cypress. When I execute the following Xpath in browser console it shows:

```
[button.ui.basic.fluid.primary.button.next]
```

Which it's correct. But when I run the same query in my Cypress test it gives:

```
[]
```

This is my test:

```js
Cypress.Commands.add("logout", () => {
	const force = { force: true }
	cy.wait(2000)
	cy.get('div > button.ui.massive.basic.inverted.button.next').click(force)
	cy.xpath('//*[@id="root"]/div/div[4]/div[1]/div/div[2]/button').click(force)
})

```

**Comment by bahmutov** [comment]
But I don’t see you doing xpath command anywhere, just cy.get that only uses jquery selector.
