### ISSUE TITLE
Can't use "cy.xpath()" with "Typescript" plugin

### ISSUE THREAD

**Issue by Ohrimenko1988** [cypress-io/cypress-xpath#28]
I am using cypress with webpack:
```
{
  "name": "cypress-tests",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cypress:open": "cypress open"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@cypress/webpack-preprocessor": "^4.0.3",
    "cypress": "^3.1.5",
    "cypress-xpath": "^1.3.0",
    "ts-loader": "^5.3.3",
    "typescript": "^3.3.3",
    "webpack": "^4.29.3"
  }

}

```

The "cypress-xpath" has been installed according to project "README" and it works with "js" files.
But with "ts" files:
 
![screenshot from 2019-02-22 16-01-22](https://user-images.githubusercontent.com/22724619/53247083-23dd4a00-36bb-11e9-93fb-3bef80b1593b.png)

Error message:
```
TS2339: Property 'xpath' does not exist on type 'Chainable<undefined>'.
```

So, how can I use "cypress-xpath" with "Typescript" plugin

**Comment by bahmutov** [comment]
you need to add this `index.d.ts` to your spec file or to your tsconfig.json file. It will extend `cy` object with this `cy.xpath` method

**Comment by smkamble** [comment]
Hi 
Could you please share tsconfig.json code for cypress-xpath

**Comment by saurabhp-onit** [comment]
Just do import "cypress-xpath" in your project's index.ts file
