### ISSUE TITLE
not able to use timeout with cy.xpath()

### ISSUE THREAD

**Issue by nishant-sngl** [cypress-io/cypress-xpath#31]
I am trying to use the below cmd for clicking an element:
```js
 cy.xpath(addBtn,{timeout: 10000}).click();
```

BUT, it fails with the below error:

```
CypressError: cy.click() failed because it requires a DOM element.
The subject received was:
  > {}
The previous command that ran was:
  > cy.xpath()
```

It seems to be not waiting for the element for 10sec. It fails instantly.
While if i use `cy.wait()` for 10 sec, then it clicks on the button.

Is the timeout supposed to work with `cy.xpath()` in the similar way it works with `cy.get()`?

**Comment by badeball** [comment]
I tried to write a [test case](https://github.com/cypress-io/cypress-xpath/compare/master...badeball:test-timeout-configuration) for this behavior, but to my surprise the test actually pass and I can't figure out why. Does `cy.verifyUpcomingAssertions` handle timeout for anyone implementing custom commands?

**Comment by roggerfe** [comment]
Having the same issue

**Comment by snehalka** [comment]
I am also facing the same issue.

**Comment by jennifer-shehane** [comment]
Clsoing as I cannot recreate this behavior. 

Please provide an HTML page with the exact example test code so that we can address the problem you are having and we will reopen.

```js
it('testing timeout fail', () => {
  // Fails after 10 seconds
  cy.visit('https://example.cypress.io/commands/actions')
  cy.xpath('//*[@id="email3"]', { timeout: 10000 }).click()
})

it('testing timeout pass', () => {
  // Passes immediately because el is found
  cy.visit('https://example.cypress.io/commands/actions')
  cy.xpath('//*[@id="email1"]', { timeout: 10000 }).click()
})
```

![](http://g.recordit.co/fXHNelYfvG.gif)
