### ISSUE TITLE
Xpath Locator information is not displayed in cypress error

### ISSUE THREAD

**Issue by vinod236** [cypress-io/cypress-xpath#59]
when we use code like `cy.xpath("//div[.='basket']")` we dont get its locator details as the way get for `cy.get` in the final result 

we get error without locator in error description , example as given below

```
CypressError: Timed out retrying: Expected to find element: '', but never found it
```

**Comment by roggerfe** [comment]
Same issue here

**Comment by mohitsingla1** [comment]
When then issue will resolve

**Comment by mohitsingla1** [comment]
@bahmutov @jennifer-shehane 
Please release version with this fix also.
Thanks,

**Comment by bahmutov** [comment]
I will be happy to merge a pull request that solves this problem, so far I did not have time to look into this issue

**Comment by mohitsingla1** [comment]
> I will be happy to merge a pull request that solves this problem, so far I did not have time to look into this issue
Thanks @bahmutov 
Please let me know i case of anything required

**Comment by mauron85** [comment]
So the PR with fix is there. Can I kindly ask for a merge?
