### ISSUE TITLE
Wait for an object to disappear

### ISSUE THREAD

**Issue by edumorata** [cypress-io/cypress-xpath#66]
Hello everyone, I am using Cypress-xpath Cypress plugin but I don't know if I can do something like this.

I want to wait for an object to disappear, I am trying to put an object in a variable and put it in a loop to know if it is visible or not and leave the loop when it is not.

If I use `cy.xpath ('xpath')` and the object exists, I can wait until it is null, but when Cypress verifies the xpath (now it is not on the screen) it breaks.

Is there any way to enter the internal cypress check and make a loop inside before the cypress verifies the object and breaks the execution? I mean something like:

```js
cy.xpath('xpath').should(($input) => {

   while ($input != null) {
      //Be into loop until the object is null
   }
})
```
Or there is a way to do this function 'waitToVanish' (my personal function name)?

If i have to do it with cypress selector i do this:

```js
const nonExistent = Cypress.$(object)
    
if (!nonExistent.length) {

    while (!finded && sec < time) {
        
        if (!nonExistent.length) {   
        
            cy.wait(1000);
            
            sec += 1000;

            cy.log("The object " + object + " does not exist");
        } 
        
        else {
            
            finded = true;
        }
    }

    if (!finded) {

        cy.log("The object " + object + " was not found after " + sec + " seconds")

        cy.xpath("/*/")
    }
}

else
    cy.log("The object " + object + " was found")
```

I tried too through `document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null ).singleNodeValue` but cypress doesn't recognize it while developer console of the browser it does

Thank you very much

**Comment by jennifer-shehane** [comment]
@edumorata Cypress automatically retries assertions until the state matches what you specify. Please read all of the Cypress documentation as this is explained in detail there. https://docs.cypress.io/guides/core-concepts/retry-ability.html

You do not need to write all of this logic yourself - this is the large benefit of Cypress. 

```js
cy.xpath('xpath').should('not.exist')

// or maybe you're waiting for it to not be visible.
cy.xpath('xpath').should('not.be.visible')
```

If you want to wait longer, increase the timeout:

```js
cy.xpath('xpath', { timeout: 20000 }).should('not.exist')
```
