### ISSUE TITLE
cy.xpath() does not work in Firefox

### ISSUE THREAD

**Issue by AutoHobo** [cypress-io/cypress-xpath#74]
### Current behavior:

Using any xpaths like example:
`//*[text()="Add Page"]`

Causes Firefox to give a security error `(SecurityError: The operation is insecure.)`, and the element is not clickable.

![Error](https://user-images.githubusercontent.com/61048155/74523287-bb632a80-4f14-11ea-8f5f-c0eaa0146364.png)

### Desired behavior:

Cypress should be able to interact with element

### Versions

Cpress 4.0.1, Windows 10, FireFox 40.0.2(32Bit)

**Comment by jennifer-shehane** [comment]
@bahmutov I similarly tried to run a simple `cy.xpath()` command in Firefox and it didn't work. 

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <div>action</div>
</body>
</html>
```

`spec.js`

```js
it('repro', () => {
  cy.visit('index.html')
  cy.xpath('/html/body/div')
})
```

<img width="497" alt="Screen Shot 2020-02-18 at 10 53 45 AM" src="https://user-images.githubusercontent.com/1271364/74703847-f75ffd80-523c-11ea-80de-14b249b53a1b.png">

**Comment by Yuliana1994** [comment]
Is there an estimated time on when this issue will be resolved?

**Comment by jennifer-shehane** [comment]
There has been no work done on this issue, with no current estimate for fixing.

**Comment by estefafdez** [comment]
Any idea when this issue is going to be fixed? thanks!

**Comment by RainerJaspert** [comment]
I would expect  that this should fix it 
```
-    let iterator = document.evaluate(selector, contextNode)
+    let iterator = contextNode.evaluate(selector, contextNode)
```
[src/index.js.55](https://github.com/cypress-io/cypress-xpath/blob/289311a59ba82517e8f7e435f78a147f02893e07/src/index.js#L55)

**Comment by bahmutov** [comment]
I am open a pull request

**Comment by bahmutov** [comment]
resolved by https://github.com/cypress-io/cypress-xpath/pull/87
