### ISSUE TITLE
Issue after forEach loop -  Error: xpath() can only be called on a single element. Your subject contained 4 elements.

### ISSUE THREAD

**Issue by lruszlewicz** [cypress-io/cypress-xpath#77]
Hi when I try to invoke xpath method after forEach I have an Issue like in subject: 
 Error: xpath() can only be called on a single element. Your subject contained 4 elements.
code is below
this.data.productName.forEach(function(element){
            cy.selectProduct(element)
        });
cy.xpath("//div[@id='navbarResponsive']//a").click()
![xpath](https://user-images.githubusercontent.com/61823457/75962852-ca5e4c80-5ec4-11ea-8e8b-558ae7f490ac.jpg)
![xpath2](https://user-images.githubusercontent.com/61823457/75962855-caf6e300-5ec4-11ea-8fe3-e40be4dde92d.jpg)

**Comment by badeball** [comment]
Might be related to https://github.com/cypress-io/cypress/issues/4921. Can you show the code for `cy.selectProduct`?

**Comment by lruszlewicz** [comment]
Sure, below is the code for selectProduct 

Cypress.Commands.add("selectProduct",function(productName){
    cy.get('h4.card-title').each(($el,index,list)=>{
        if($el.text().includes(productName)){
            cy.get('button.btn.btn-info').eq(index).click()
        }
    })
});

**Comment by badeball** [comment]
It seems like you are in fact affected by this bug. Can you try adding a `cy.wrap(null);` in between, as shown below?

```js
this.data.productName.forEach(function(element) {
  cy.selectProduct(element);
});
cy.wrap(null);
cy.xpath("//div[@id='navbarResponsive']//a").click();
```

**Comment by lruszlewicz** [comment]
works correctly after wrap()
