### ISSUE TITLE
install with yarn

### ISSUE THREAD

**Issue by Camineet** [cypress-io/cypress-xpath#89]
Hi as part of a course I'm taking, I'm practicing with an app that breaks for some reason whenever I use npm with it. It's this app:

https://github.com/gothinkster/angular-realworld-example-app

So, I have to use yarn for everything with this app. I've installed cypress-xpath with yarn, and it seems to work. Can you add yarn install instructions to the readme?

Great extension by the way.

**Comment by jennifer-shehane** [comment]
The repo is open source, so we're welcome to a PR!

**Comment by bahmutov** [comment]
The install instructions are there, see https://github.com/cypress-io/cypress-xpath#install-with-yarn Thanks @jennifer-shehane
