### ISSUE TITLE
Not able to pick xpath from the fixture folder 

### ISSUE THREAD

**Issue by manalisha123** [cypress-io/cypress-xpath#98]
Not able to pick xpath from the fixture folder .
Xpath is installed in the parent folder itself for the my scenario
It's giving type error

```
TypeError
Cannot read property 'ORCreateNewCommercialCustomer' of undefined
```

Only hard code is working

![image](https://user-images.githubusercontent.com/48355699/84480034-88a62480-acb1-11ea-936a-f70c6f2b2646.png)

**Comment by jennifer-shehane** [comment]
@manalisha123 We'll need a fully reproducible example in order to investigate. We can't tell where this variable is being called or why it's parent is undefined from the information given. Please provide an example and we will consider reopening.

**Comment by manalisha123** [comment]
Hi Jenifer
Steps:
1. I have a Xpath which I kept in our Repo folder inside fixtures.
2.I have other CSS locators also stored in the same file
Path will look like:
![image](https://user-images.githubusercontent.com/48355699/84511742-9aed8600-ace4-11ea-9205-b9dbe15df002.png)

My xpath is:
"plusSymbol":"//div[@class='c-navigatorItem-faceplate ng-scope ng-isolate-scope']"

Interestingly if use the same xpath directly in my code inside integration folder it  is working perfectly fine.
But if I use it via one variable which is stored in the fixture folder it is not able to pick it.
Code snippet is below as mentioned.
![image](https://user-images.githubusercontent.com/48355699/84511906-dc7e3100-ace4-11ea-809f-dda73b0e28d8.png)
