### ISSUE TITLE
Not able to pick xpath from the fixture folder  as parameter in Integration scripts

### ISSUE THREAD

**Issue by manalisha123** [cypress-io/cypress-xpath#99]
Not able to pick xpath from the fixture folder as parameter in Integration scripts
Steps:
1.I have a Xpath which I kept in our Repo folder inside fixtures.
2.I have other CSS locators also stored in the same file
Path will look like:
![image](https://user-images.githubusercontent.com/48355699/84735323-df1ca700-afc0-11ea-9d05-05ace604b65e.png)

My xpath which is stored in the fixture folder :
"plusSymbol":"//div[@Class='c-navigatorItem-faceplate ng-scope ng-isolate-scope']"

Interestingly if use the same xpath directly in my code inside integration folder it is working perfectly fine.
But if I use it via one variable which is stored in the fixture folder it is not able to pick it.
Code snippet is below as mentioned.
![image](https://user-images.githubusercontent.com/48355699/84735384-05424700-afc1-11ea-919d-e68670473bf6.png)

It's pretty simple scenario where instead of hardcoding xpath  directly in integration scripts just need to get it called from fixture folder.
Store it in a variable and call the variable in integration folder.
![image](https://user-images.githubusercontent.com/48355699/84735435-29058d00-afc1-11ea-9bfa-d32d27c3a34f.png)

**Comment by badeball** [comment]
This isn't a problem with `cypress-xpath`, but rather likely due to the fact that you're using arrow functions and binding `this` to something unexpected.

**Comment by jennifer-shehane** [comment]
Yes, you'll need to update your arrow functions to `function` syntax https://on.cypress.io/variables-and-aliases#Avoiding-the-use-of-this
